project:
  type: website

website:
  title: "Nate's Website"
  navbar:
    left:
      - text: "Tools"
      - menu:
        - href: index.qmd
          text: Home Link
        - href: about.qmd
          text: About Link

    right: 
      - href: about.qmd
        text: About
      - icon: bank

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



